#!/bin/bash

#This script is the entry point for handling nodes that fail to boot. 
#It is called automatically by slurm after the resume timeout

#get environment settings
test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/functions ] && . $SHC4HPCBASE/lib/functions


log handling failure for nodes $1 

for node in $(/apps/system/slurm/latest/bin/scontrol show hostnames "$1" )
do
  /apps/system/slurm/SHC4HPC/bin/slurm_fail_helper_client $node&
  log fail $node 
done

