#!/bin/bash
DRACMAPS=$SHC4HPCBASE/etc/shc4hpc/idracmaps
DELLBASE=${DELLBASE:-/opt/dell/srvadmin}

export LD_LIBRARY_PATH=$DELL/lib64:$DELL/lib64/openmanage/private

node2rac ()
{
   number=$(grep ^"${1}:" $DRACMAPS | awk -F : '{ print $2 }' )
   if [ $? -ne 0 ] ; then
     error Slurm resume of $1 requires rac ip entered into $DRACMAPS
     exit 1
   fi
   echo $number
}
creds()
{
   usertest=$(grep ^"${1}:" $DRACMAPS | awk -F : '{ print $3 }' )
   passtest=$(grep ^"${1}:" $DRACMAPS | awk -F : '{ print $4 }' )
   user=${usertest:-root}
   pass=${passtest:-calvin}
   echo -u $user -p $pass
}
node=$1
racip=$(node2rac $node)
if [ $? -ne 0 ] || [ -z $racip ]; then
  exit 1
fi


CREDS=$(creds $node)

#Try powering it down if it is not actually contactable
#ssh -o ConnectTimeout=5 -i /usr/lib/slurm/id_slurm $node hostname  || $DELL/bin/idracadm7 $CREDS -r $racip serveraction powerdown
info   "$DELLBASE/bin/idracadm7 $CREDS -r $racip serveraction powerup"
$DELLBASE/bin/idracadm7 $CREDS -r $racip serveraction powerup 
if [ $? -ne 0 ]; then 
   warning "$DELLBASE/bin/idracadm7 $CREDS -r $racip serveraction powerup failed - its possible the server is already on or it failed to connect to $racip?"
fi
exit 0
   


