#!/bin/bash


DIR=$(dirname $(realpath $0) )
pwd=$PWD
cd $DIR

. environ

SHC4HPCBASE=${SHC4HPCBASE:-/usr/lib/shc4hpc}
SHC4HPCSYSCONFIG="${SHC4HPCSYSCONFIG:-/etc/sysconfig/shc4hpc}"
test -f $SHC4HPCSYSCONFIG && . $SHC4HPCSYSCONFIG
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/core/functions ] && . $SHC4HPCBASE/lib/core/functions


PACKERIO=$SHC4HPCBASE/bin/packer

cd ../../imagebuild/files/baseimage
tar czf ../baseimageblob.tgz ./ 
cd ../shc4hpc
rsync -a $SHC4HPCBASE/lib/ lib/
tar czf ../shc4hpcblob.tgz ./ 
cd ../userdefined
tar czf ../userdefinedblob.tgz ./
cd ../..
echo $AZ_IMAGE_RG
${PACKERIO} build templates/az_centos_example2.json
cd $pwd
