#!/bin/bash 

#This script is the entry point for handling node resuming
#It is called automatically by slurm after the resume timeout

#get environment settings
SHC4HPCBASE=${SHC4HPCBASE:-/usr/lib/shc4hpc}
test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment 
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/core/functions ] && . $SHC4HPCBASE/lib/core/functions

for node in $(/apps/system/slurm/latest/bin/scontrol show hostnames "$1" ) ; do 
   info resume node $q
   $SHC4HPCBASE/handlers/resume/node_resume_helper $1&
done
exit 0
