#!/bin/bash -x
echo STARTING SCRIPT BASEPACKAGES
if [[ -x /usr/bin/yum ]]; then
	INST="sudo yum -y install"
	$INST  epel-release yum-utils
	sudo yum -y makecache
elif [[ -x /usr/bin/zypper ]] ; then
	INST="sudo zypper -n install"
	$INST wget mlocate ntp
	$INST realmd sssd sssd-krb5 
fi

#TODO Base packages for SLES

#df
sudo sed 's/server 3.centos.pool.ntp.org iburst/server 192.168.126.2  iburst/' /etc/ntp.conf | sudo tee /etc/ntp.conf.tmp
sudo mv /etc/ntp.conf.tmp /etc/ntp.conf
echo FINISH SCRIPT BASEPACKAGES
