#!/bin/bash
cd /
#force ownership to root though
sudo tar -tzf /tmp/userdefinedblob.tgz
mkdir /tmp/unpack
sudo tar -xzf /tmp/userdefinedblob.tgz -C /tmp/unpack
sudo chown root:root /tmp/unpack -R
sudo chmod g-w /tmp/unpack -R
cd /tmp/unpack
sudo rsync -a ./ /
