#!/bin/bash
cd /
#force ownership to root though
sudo tar -tzf /tmp/shc4hpcblob.tgz

TMPDIR=/tmp/unpack
SHC4HPCBASE=${SHC4HPCBASE:-/usr/lib/shc4hpc}
test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/core/functions ] && . $SHC4HPCBASE/lib/core/functions


SYSDIR=$SHC4HPCBASE
DSTDIR=$TMPDIR/$SYSDIR

sudo mkdir -m 755 -p $DSTDIR $SYSDIR 

sudo tar -xzf /tmp/shc4hpcblob.tgz -C $DSTDIR

sudo chown root:root $DSTDIR -R
sudo chmod g-w $DSTDIR -R
sudo chown root:root $SYSDIR -R
sudo chmod g-w $SYSDIR -R

cd $DSTDIR

sudo rsync -a ./ $SYSDIR/
