#!/bin/bash
cd /
#force ownership to root though
sudo tar -tzf /tmp/userdefinedblob.tgz
mkdir -m 700 /tmp/unpack2
sudo tar -xzf /tmp/userdefinedblob.tgz -C /tmp/unpack2
sudo chown root:root /tmp/unpack2 -R
sudo chmod g-w /tmp/unpack2 -R
cd /tmp/unpack2
cd  secrets/generated
sudo rsync -a ./ /
cd ../..
cd  secrets/manual
sudo rsync -a ./ /
cd ../..
cd  public/generated
sudo rsync -a ./ /
cd ../..
cd  public/secrets
sudo rsync -a ./ /
cd ../..
