#!/bin/bash 

#This script is the entry point for handling node suspend and deallocation
#It is called automatically by slurm after the resume timeout

#get environment settings
test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment 
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/functions ] && . $SHC4HPCBASE/lib/functions


for node in $(/apps/system/slurm/latest/bin/scontrol show hostnames "$1" ) ; do 
   info suspend node $1
   $SHC4HPCBASE/handlers/suspend/node_suspend_helper $1&
done
exit 0
