#!/bin/bash 
#This script handles actions for specific nodes that fail to resume after resume timeout
#it is not meant to be called directly
#get environment settings
test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/functions ] && . $SHC4HPCBASE/lib/functions


node=$1
info resuming $node 
nodetype=$(nodetype $node)
info the node type is $nodetype
exec $SHC4HPCBASE/handlers/resume/$nodetype/resume $node


