#!/bin/bash
#get environment settings
test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/functions ] && . $SHC4HPCBASE/lib/functions



DRACMAPS=$SHC4HPCBASE/etc/shc4hpc/idracmaps
DELLBASE=${DELLBASE:-/opt/dell/srvadmin}

export LD_LIBRARY_PATH=$DELLBASE/lib64:$DELLBASE/lib64/openmanage/private
debug "Running failconnect for dell"
node2rac ()
{
   number=$(grep ^"${1}:" $DRACMAPS | awk -F : '{ print $2 }' )
   if [ $? -ne 0 ] ; then
     error "Slurm resume of $1 requires rac ip entered into $DRACMAPS"
     exit 1
   fi
   echo $number
}
creds()
{
   usertest=$(grep ^"${1}:" $DRACMAPS | awk -F : '{ print $3 }' )
   passtest=$(grep ^"${1}:" $DRACMAPS | awk -F : '{ print $4 }' )
   user=${usertest:-root}
   pass=${passtest:-calvin}
   echo -u $user -p $pass
}
node=$1
node2rac $node
echo $node 
racip=$(node2rac $node)
if [ $? -ne 0 ] || [ -z $racip ]; then
  error "Gettig rac ip for $node"  
  exit 1
fi


CREDS=$(creds $node)

#Try powering it down if it is not actually contactable
#ssh -o ConnectTimeout=5 -i /usr/lib/slurm/id_slurm $node hostname  || $DELL/bin/idracadm7 $CREDS -r $racip serveraction powerdown
info  "$DELLBASE/bin/idracadm7 $CREDS -r $racip serveraction powerdown"
$DELLBASE/bin/idracadm7 $CREDS -r $racip serveraction powerdown
if [ $? -ne 0 ]; then 
   warning "$DELLBASE/bin/idracadm7 $CREDS -r $racip serveraction powerdown failed - its possible the server is already off or it failed to connect to $racip?"
fi
exit 0
   


