#!/bin/bash 

#This script is the entry point for handling node suspend and deallocation
#It is called automatically by slurm after the resume timeout

#get environment settings
SHC4HPCBASE=${SHC4HPCBASE:-/usr/lib/shc4hpc}

test -f /etc/sysconfig/shc4hpc && . /etc/sysconfig/shc4hpc
[ -n $SHC4HPCBASE ] && [ -f  $SHC4HPCBASE/etc/shc4hpc/environment ] && . $SHC4HPCBASE/etc/shc4hpc/environment 
[ -n $SHC4HPCBASE ] &&  [ -f  $SHC4HPCBASE/lib/core/functions ] && . $SHC4HPCBASE/lib/core/functions


for node in $( $SLURMBASE/bin/scontrol show hostnames "$1" ) ; do 
   info suspend node $node
   $SHC4HPCBASE/handlers/suspend/node_suspend_helper $node
done
exit 0
